/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.Empresa;
import DAO.EmpresasCRUD;
import Modelo.EmpresaM;
import Modelo.Conexion;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author InaRu
 */
public class EmpresasView extends javax.swing.JPanel {

private String accion = "guardar";
    /**
     * Creates new form Empresas
     */
    public EmpresasView() {
        initComponents();
        mostrar("");
        codigo_txt.setEnabled(false);
         //inhabilitar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_listadoEmpresa = new javax.swing.JPanel();
        desc_jtxt = new javax.swing.JTextField();
        nomEmpresalbl1 = new javax.swing.JLabel();
        codigo_txt = new javax.swing.JTextField();
        nomEmpresalbl = new javax.swing.JLabel();
        limpiarbtn = new javax.swing.JButton();
        agregarEmpresabtn3 = new javax.swing.JButton();
        codigoE_lbl = new javax.swing.JLabel();
        nom_empres_txt = new javax.swing.JTextField();
        jP_datosEmpresa1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablaEmpresas = new javax.swing.JTable();
        eliminarEmpresabtn = new javax.swing.JButton();
        modEmpresabtn = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txt_buscarEm = new javax.swing.JTextField();
        salirbtn = new javax.swing.JButton();

        setBackground(java.awt.SystemColor.controlHighlight);
        setMaximumSize(new java.awt.Dimension(750, 550));
        setMinimumSize(new java.awt.Dimension(750, 550));
        setPreferredSize(new java.awt.Dimension(750, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jP_listadoEmpresa.setBackground(java.awt.SystemColor.controlHighlight);
        jP_listadoEmpresa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 153, 255)), "Datos empresa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), javax.swing.UIManager.getDefaults().getColor("Actions.Blue"))); // NOI18N
        jP_listadoEmpresa.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));

        desc_jtxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        desc_jtxt.setMaximumSize(new java.awt.Dimension(64, 22));

        nomEmpresalbl1.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        nomEmpresalbl1.setText("Descripción :");

        codigo_txt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        codigo_txt.setOpaque(true);

        nomEmpresalbl.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        nomEmpresalbl.setText("Nombre empresa:");

        limpiarbtn.setBackground(new java.awt.Color(0, 153, 204));
        limpiarbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        limpiarbtn.setForeground(new java.awt.Color(255, 255, 255));
        limpiarbtn.setText("Limpiar");
        limpiarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarbtnActionPerformed(evt);
            }
        });

        agregarEmpresabtn3.setBackground(new java.awt.Color(0, 153, 204));
        agregarEmpresabtn3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        agregarEmpresabtn3.setForeground(new java.awt.Color(255, 255, 255));
        agregarEmpresabtn3.setText("Agregar");
        agregarEmpresabtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEmpresabtn3ActionPerformed(evt);
            }
        });

        codigoE_lbl.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        codigoE_lbl.setText("Código empresa:");

        nom_empres_txt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nom_empres_txt.setOpaque(true);

        javax.swing.GroupLayout jP_listadoEmpresaLayout = new javax.swing.GroupLayout(jP_listadoEmpresa);
        jP_listadoEmpresa.setLayout(jP_listadoEmpresaLayout);
        jP_listadoEmpresaLayout.setHorizontalGroup(
            jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_listadoEmpresaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_listadoEmpresaLayout.createSequentialGroup()
                        .addComponent(codigoE_lbl)
                        .addGap(24, 24, 24)
                        .addComponent(codigo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jP_listadoEmpresaLayout.createSequentialGroup()
                        .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomEmpresalbl)
                            .addComponent(nomEmpresalbl1))
                        .addGap(18, 18, 18)
                        .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(desc_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nom_empres_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agregarEmpresabtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpiarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        jP_listadoEmpresaLayout.setVerticalGroup(
            jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_listadoEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarEmpresabtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoE_lbl)
                    .addComponent(codigo_txt))
                .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_listadoEmpresaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(limpiarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jP_listadoEmpresaLayout.createSequentialGroup()
                        .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomEmpresalbl)
                            .addGroup(jP_listadoEmpresaLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(nom_empres_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jP_listadoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP_listadoEmpresaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(desc_jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(jP_listadoEmpresaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomEmpresalbl1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        add(jP_listadoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, 720, 140));

        jP_datosEmpresa1.setBackground(java.awt.SystemColor.controlHighlight);
        jP_datosEmpresa1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Listado empresas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), javax.swing.UIManager.getDefaults().getColor("Actions.Blue"))); // NOI18N
        jP_datosEmpresa1.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));

        jTablaEmpresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Descripción"
            }
        ));
        jTablaEmpresas.setColumnSelectionAllowed(true);
        jTablaEmpresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaEmpresasMouseClicked(evt);
            }
        });
        jTablaEmpresas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTablaEmpresasKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTablaEmpresas);
        jTablaEmpresas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        eliminarEmpresabtn.setBackground(new java.awt.Color(0, 153, 204));
        eliminarEmpresabtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eliminarEmpresabtn.setForeground(new java.awt.Color(255, 255, 255));
        eliminarEmpresabtn.setText("Eliminar");
        eliminarEmpresabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEmpresabtnActionPerformed(evt);
            }
        });

        modEmpresabtn.setBackground(new java.awt.Color(0, 153, 204));
        modEmpresabtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        modEmpresabtn.setForeground(new java.awt.Color(255, 255, 255));
        modEmpresabtn.setText("Modificar");
        modEmpresabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modEmpresabtnActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(0, 153, 204));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        salirbtn.setBackground(new java.awt.Color(0, 153, 204));
        salirbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        salirbtn.setForeground(new java.awt.Color(255, 255, 255));
        salirbtn.setText("Salir");
        salirbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_datosEmpresa1Layout = new javax.swing.GroupLayout(jP_datosEmpresa1);
        jP_datosEmpresa1.setLayout(jP_datosEmpresa1Layout);
        jP_datosEmpresa1Layout.setHorizontalGroup(
            jP_datosEmpresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_datosEmpresa1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jP_datosEmpresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                    .addComponent(txt_buscarEm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jP_datosEmpresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eliminarEmpresabtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modEmpresabtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salirbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jP_datosEmpresa1Layout.setVerticalGroup(
            jP_datosEmpresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_datosEmpresa1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jP_datosEmpresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(txt_buscarEm))
                .addGap(18, 18, 18)
                .addGroup(jP_datosEmpresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jP_datosEmpresa1Layout.createSequentialGroup()
                        .addComponent(modEmpresabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarEmpresabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salirbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        add(jP_datosEmpresa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 154, 720, 370));
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarbtnActionPerformed
        
        habilitar();
        nom_empres_txt.setText("");
        desc_jtxt.setText("");
        codigo_txt.setText("");
    }//GEN-LAST:event_limpiarbtnActionPerformed

    private void agregarEmpresabtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEmpresabtn3ActionPerformed
         codigo_txt.setEnabled(false);
         accion="guardar"; 
         
         if (nom_empres_txt.getText().length() == 0) {
            JOptionPane.showConfirmDialog(null, "Debes ingresar un nombre de empresa");
            nom_empres_txt.requestFocus();
            return;
        }
        
        EmpresaM edatos=new EmpresaM();
        EmpresasCRUD em=new EmpresasCRUD();
        
        edatos.setNom_empresa(nom_empres_txt.getText());
        edatos.setDescr(desc_jtxt.getText());
        
        if(accion.equals("guardar")){
            if(em.anyadirEmpresa(edatos)){
                JOptionPane.showMessageDialog(null, "La empresa ha sido agregada satisfactoriamente");
               
            }
                     
        }
        
        
    }//GEN-LAST:event_agregarEmpresabtn3ActionPerformed

    private void eliminarEmpresabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEmpresabtnActionPerformed
         
        codigo_txt.setEnabled(false);    
        int fila = jTablaEmpresas.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(null,"Usuario no Seleccionado");
        } else {
            if (!codigo_txt.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(null, 
                "Estás seguro de Eliminar a la empresa?","Confirmar",2);
            
            if (confirmacion==0) {
                EmpresasCRUD e = new EmpresasCRUD();
                EmpresaM em= new EmpresaM();
                
                em.setID_empresa(Integer.parseInt(codigo_txt.getText()));
                e.eliminarEmpresa(em);
                mostrar("");
                
                
            } 
        }
    }//GEN-LAST:event_eliminarEmpresabtnActionPerformed
    }
    private void modEmpresabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modEmpresabtnActionPerformed
        accion="Modificar"; 
        codigo_txt.setEnabled(false); 
         if (nom_empres_txt.getText().length() == 0) {
            JOptionPane.showConfirmDialog(null, "Debes ingresar un nombre de empresa");
            nom_empres_txt.requestFocus();
            return;
        }
        
        EmpresaM edatos=new EmpresaM();
        EmpresasCRUD em=new EmpresasCRUD();
        
        edatos.setNom_empresa(nom_empres_txt.getText());
        edatos.setDescr(desc_jtxt.getText());
        
        if ( accion.equals("Modificar")){
            edatos.setID_empresa(Integer.parseInt(codigo_txt.getText()));
            
            if(em.modificarEmpresa(edatos)){
                 JOptionPane.showMessageDialog(null, "La empresa ha sido modificada satisfactoriamente");
                 mostrar("");
                 
            }
            
        }
    }//GEN-LAST:event_modEmpresabtnActionPerformed

    private void jTablaEmpresasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablaEmpresasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablaEmpresasKeyPressed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        mostrar(txt_buscarEm.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
         mostrar(txt_buscarEm.getText());
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void salirbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirbtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirbtnActionPerformed

    private void jTablaEmpresasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaEmpresasMouseClicked
        codigo_txt.setEnabled(false);
        accion="Modificar";
        int fila = jTablaEmpresas.rowAtPoint(evt.getPoint());
        
        codigo_txt.setText(jTablaEmpresas.getValueAt(fila, 0).toString());
        nom_empres_txt.setText(jTablaEmpresas.getValueAt(fila, 1).toString());
        desc_jtxt.setText(jTablaEmpresas.getValueAt(fila, 2).toString());
    }//GEN-LAST:event_jTablaEmpresasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarEmpresabtn3;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel codigoE_lbl;
    private javax.swing.JTextField codigo_txt;
    private javax.swing.JTextField desc_jtxt;
    private javax.swing.JButton eliminarEmpresabtn;
    private javax.swing.JPanel jP_datosEmpresa1;
    private javax.swing.JPanel jP_listadoEmpresa;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablaEmpresas;
    private javax.swing.JButton limpiarbtn;
    private javax.swing.JButton modEmpresabtn;
    private javax.swing.JLabel nomEmpresalbl;
    private javax.swing.JLabel nomEmpresalbl1;
    private javax.swing.JTextField nom_empres_txt;
    private javax.swing.JButton salirbtn;
    private javax.swing.JTextField txt_buscarEm;
    // End of variables declaration//GEN-END:variables


void habilitar() {
      
        nom_empres_txt.setEnabled(true);
        desc_jtxt.setEnabled(true);
        codigo_txt.setEnabled(false);
      
        limpiarbtn.setEnabled(true);
        agregarEmpresabtn3.setEnabled(true);
        eliminarEmpresabtn.setEnabled(true);
        modEmpresabtn.setEnabled(true);
        
        nom_empres_txt.setText("");
        desc_jtxt.setText("");
}

void inhabilitar() {
     
    
        nom_empres_txt.setEnabled(false);
        desc_jtxt.setEnabled(false);
      
        limpiarbtn.setEnabled(false);
        agregarEmpresabtn3.setEnabled(false);
        eliminarEmpresabtn.setEnabled(false);
        modEmpresabtn.setEnabled(false);
        
        codigo_txt.setText("");
        desc_jtxt.setText("");
        nom_empres_txt.setText("");
        
        
        

    }

void mostrar(String buscar) {
        try {
            DefaultTableModel modelo;
            EmpresasCRUD em = new EmpresasCRUD();
            modelo= em.mostrar(buscar);

            jTablaEmpresas.setModel(modelo);

        } catch (Exception e) {
            Component rootPane = null;
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }





}
