/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author InaRu
 */
public class FacturasView extends javax.swing.JPanel {

    /**
     * Creates new form ProyectosView
     */
    public FacturasView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionesProy_jpnl = new javax.swing.JPanel();
        nuevaFAC_btn = new javax.swing.JButton();
        editFAC_btn = new javax.swing.JButton();
        eliminarFAC_btn = new javax.swing.JButton();
        guardarFAC_btn = new javax.swing.JButton();
        salir_btn = new javax.swing.JButton();
        listaProy_jpnl = new javax.swing.JPanel();
        buscarFAC_txt = new javax.swing.JTextField();
        buscarFAC_btn = new javax.swing.JButton();
        jScrollP_Proy = new javax.swing.JScrollPane();
        facturas_jTbl = new javax.swing.JTable();
        datosPR_pnl = new javax.swing.JPanel();
        codPR_lbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        idFAC_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        totalFAC_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fechaFAC_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nomFAC_txt = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBackground(java.awt.SystemColor.controlHighlight);
        setMaximumSize(new java.awt.Dimension(750, 550));
        setMinimumSize(new java.awt.Dimension(750, 550));
        setPreferredSize(new java.awt.Dimension(750, 550));

        opcionesProy_jpnl.setBackground(java.awt.SystemColor.controlHighlight);
        opcionesProy_jpnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 102, 204))); // NOI18N

        nuevaFAC_btn.setBackground(new java.awt.Color(0, 153, 204));
        nuevaFAC_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nuevaFAC_btn.setForeground(new java.awt.Color(255, 255, 255));
        nuevaFAC_btn.setText("Nueva");
        nuevaFAC_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaFAC_btnActionPerformed(evt);
            }
        });

        editFAC_btn.setBackground(new java.awt.Color(0, 153, 204));
        editFAC_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editFAC_btn.setForeground(new java.awt.Color(255, 255, 255));
        editFAC_btn.setText("Editar");

        eliminarFAC_btn.setBackground(new java.awt.Color(0, 153, 204));
        eliminarFAC_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eliminarFAC_btn.setForeground(new java.awt.Color(255, 255, 255));
        eliminarFAC_btn.setText("Eliminar");

        guardarFAC_btn.setBackground(new java.awt.Color(0, 153, 204));
        guardarFAC_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        guardarFAC_btn.setForeground(new java.awt.Color(255, 255, 255));
        guardarFAC_btn.setText("Guardar");
        guardarFAC_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarFAC_btnActionPerformed(evt);
            }
        });

        salir_btn.setBackground(new java.awt.Color(0, 153, 204));
        salir_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        salir_btn.setForeground(new java.awt.Color(255, 255, 255));
        salir_btn.setText("Salir");
        salir_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout opcionesProy_jpnlLayout = new javax.swing.GroupLayout(opcionesProy_jpnl);
        opcionesProy_jpnl.setLayout(opcionesProy_jpnlLayout);
        opcionesProy_jpnlLayout.setHorizontalGroup(
            opcionesProy_jpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opcionesProy_jpnlLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(opcionesProy_jpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salir_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardarFAC_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarFAC_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editFAC_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevaFAC_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        opcionesProy_jpnlLayout.setVerticalGroup(
            opcionesProy_jpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesProy_jpnlLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(nuevaFAC_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editFAC_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eliminarFAC_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(guardarFAC_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salir_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listaProy_jpnl.setBackground(java.awt.SystemColor.controlHighlight);
        listaProy_jpnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista facturas:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 204))); // NOI18N

        buscarFAC_btn.setBackground(new java.awt.Color(0, 153, 204));
        buscarFAC_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buscarFAC_btn.setForeground(new java.awt.Color(255, 255, 255));
        buscarFAC_btn.setText("Buscar");
        buscarFAC_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarFAC_btnActionPerformed(evt);
            }
        });

        facturas_jTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "12-6-2022", "22001_Roche_AB", "2201P_AB Roche", "1500"},
                {"2", "10-5-2022", "21013_AZ", "21013_AZ_SlideKit", "2575"},
                {null, null, null, null, null},
                {null, null, null, null, ""}
            },
            new String [] {
                "ID", "Fecha", "Nombre", "Propuesta", "Total"
            }
        ));
        facturas_jTbl.setCellSelectionEnabled(true);
        jScrollP_Proy.setViewportView(facturas_jTbl);

        javax.swing.GroupLayout listaProy_jpnlLayout = new javax.swing.GroupLayout(listaProy_jpnl);
        listaProy_jpnl.setLayout(listaProy_jpnlLayout);
        listaProy_jpnlLayout.setHorizontalGroup(
            listaProy_jpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaProy_jpnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listaProy_jpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listaProy_jpnlLayout.createSequentialGroup()
                        .addComponent(jScrollP_Proy, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(listaProy_jpnlLayout.createSequentialGroup()
                        .addComponent(buscarFAC_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarFAC_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        listaProy_jpnlLayout.setVerticalGroup(
            listaProy_jpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaProy_jpnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listaProy_jpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarFAC_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarFAC_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollP_Proy, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        datosPR_pnl.setBackground(java.awt.SystemColor.controlHighlight);
        datosPR_pnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 204))); // NOI18N

        codPR_lbl.setText("ID:");

        jLabel1.setText("Nombre:");

        idFAC_txt.setEnabled(false);
        idFAC_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFAC_txtActionPerformed(evt);
            }
        });

        jLabel2.setText("Total:");

        jLabel3.setText("Fecha: ");

        jLabel7.setText("Propuesta:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "22001_20220613_Roche_AB", "21016_20220523_AZ_Slide Kit ", " " }));

        javax.swing.GroupLayout datosPR_pnlLayout = new javax.swing.GroupLayout(datosPR_pnl);
        datosPR_pnl.setLayout(datosPR_pnlLayout);
        datosPR_pnlLayout.setHorizontalGroup(
            datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosPR_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(codPR_lbl)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomFAC_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addComponent(idFAC_txt)
                    .addComponent(fechaFAC_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalFAC_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        datosPR_pnlLayout.setVerticalGroup(
            datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosPR_pnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codPR_lbl)
                    .addComponent(idFAC_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fechaFAC_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomFAC_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totalFAC_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datosPR_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionesProy_jpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(listaProy_jpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(datosPR_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(opcionesProy_jpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaProy_jpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nuevaFAC_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaFAC_btnActionPerformed

    }//GEN-LAST:event_nuevaFAC_btnActionPerformed

    private void guardarFAC_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarFAC_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarFAC_btnActionPerformed

    private void salir_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salir_btnActionPerformed

    private void idFAC_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFAC_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFAC_txtActionPerformed

    private void buscarFAC_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarFAC_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarFAC_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarFAC_btn;
    private javax.swing.JTextField buscarFAC_txt;
    private javax.swing.JLabel codPR_lbl;
    private javax.swing.JPanel datosPR_pnl;
    private javax.swing.JButton editFAC_btn;
    private javax.swing.JButton eliminarFAC_btn;
    private javax.swing.JTable facturas_jTbl;
    private javax.swing.JTextField fechaFAC_txt;
    private javax.swing.JButton guardarFAC_btn;
    private javax.swing.JTextField idFAC_txt;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollP_Proy;
    private javax.swing.JPanel listaProy_jpnl;
    private javax.swing.JTextField nomFAC_txt;
    private javax.swing.JButton nuevaFAC_btn;
    private javax.swing.JPanel opcionesProy_jpnl;
    private javax.swing.JButton salir_btn;
    private javax.swing.JTextField totalFAC_txt;
    // End of variables declaration//GEN-END:variables
}
