/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.BorderLayout;
import java.awt.Container;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author InaRu
 */
public class Home extends javax.swing.JFrame {

    private Container contenedor;
    private JPanel panel;
    
    
    
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        //UsuariosView u = new UsuariosView();
        //JFrame jf= new JFrame();
        //jf.getContentPane().add(u);
        
        UsuariosView user= new UsuariosView();
        ShowPanel(user);
        
        
    }
    
    /**
     * Método para llamar los formularios que quiero mostrar en el contenido del jFrame
     * Parametro de entrada es el jPanel que queremos mostrar
     */
    private void ShowPanel(JPanel jp){
        
        jp.setSize(750,550);
        jp.setLocation(0, 0);
        
        content_jpnl.removeAll();
        content_jpnl.add(jp, BorderLayout.CENTER);
        content_jpnl.revalidate();
        content_jpnl.repaint();
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        content_jpnl = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jM_Empresas = new javax.swing.JMenu();
        jM_usuarios = new javax.swing.JMenu();
        jM_Proyectos = new javax.swing.JMenu();
        jM_tareas = new javax.swing.JMenu();
        jM_clientes = new javax.swing.JMenu();
        jM_fact = new javax.swing.JMenu();
        jM_informes = new javax.swing.JMenu();
        Salir_menu = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 255));
        setMinimumSize(new java.awt.Dimension(38, 38));
        setName("frameHome"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        content_jpnl.setBackground(java.awt.SystemColor.controlHighlight);
        content_jpnl.setMaximumSize(new java.awt.Dimension(750, 550));
        content_jpnl.setMinimumSize(new java.awt.Dimension(750, 550));
        content_jpnl.setName(""); // NOI18N
        content_jpnl.setPreferredSize(new java.awt.Dimension(750, 550));
        getContentPane().add(content_jpnl, "cardContenido");

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 204));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.setMaximumSize(new java.awt.Dimension(390, 32768));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(446, 33));
        jMenuBar1.setOpaque(true);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(446, 33));

        jM_Empresas.setText("Empresas");
        jM_Empresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jM_EmpresasMouseClicked(evt);
            }
        });
        jMenuBar1.add(jM_Empresas);

        jM_usuarios.setText("Usuarios");
        jM_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jM_usuariosMouseClicked(evt);
            }
        });
        jMenuBar1.add(jM_usuarios);

        jM_Proyectos.setText("Proyectos");
        jM_Proyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jM_ProyectosMouseClicked(evt);
            }
        });
        jMenuBar1.add(jM_Proyectos);

        jM_tareas.setText("Tareas");
        jM_tareas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jM_tareasMouseClicked(evt);
            }
        });
        jMenuBar1.add(jM_tareas);

        jM_clientes.setText("Clientes");
        jM_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jM_clientesMouseClicked(evt);
            }
        });
        jMenuBar1.add(jM_clientes);

        jM_fact.setText("Facturación");
        jM_fact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jM_factMouseClicked(evt);
            }
        });
        jMenuBar1.add(jM_fact);

        jM_informes.setText("Informes ");
        jMenuBar1.add(jM_informes);

        Salir_menu.setText("Salir");
        Salir_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Salir_menuMouseClicked(evt);
            }
        });
        jMenuBar1.add(Salir_menu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jM_EmpresasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jM_EmpresasMouseClicked
        EmpresasView em= new EmpresasView();
        ShowPanel(em);
    }//GEN-LAST:event_jM_EmpresasMouseClicked

    private void jM_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jM_usuariosMouseClicked
        UsuariosView user= new UsuariosView();
        ShowPanel(user);
    }//GEN-LAST:event_jM_usuariosMouseClicked

    private void jM_ProyectosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jM_ProyectosMouseClicked
        ProyectosView pr= new ProyectosView();
        ShowPanel(pr);
    }//GEN-LAST:event_jM_ProyectosMouseClicked

    private void jM_tareasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jM_tareasMouseClicked
        TareasView pr= new TareasView();
        ShowPanel(pr);
    }//GEN-LAST:event_jM_tareasMouseClicked

    private void jM_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jM_clientesMouseClicked
        ClientesView pr= new ClientesView();
        ShowPanel(pr);
    }//GEN-LAST:event_jM_clientesMouseClicked

    private void jM_factMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jM_factMouseClicked
       FacturasView pr= new FacturasView();
        ShowPanel(pr);
    }//GEN-LAST:event_jM_factMouseClicked

    private void Salir_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salir_menuMouseClicked
        System.exit(0);
    }//GEN-LAST:event_Salir_menuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Salir_menu;
    private javax.swing.JPanel content_jpnl;
    private javax.swing.JMenu jM_Empresas;
    private javax.swing.JMenu jM_Proyectos;
    private javax.swing.JMenu jM_clientes;
    private javax.swing.JMenu jM_fact;
    private javax.swing.JMenu jM_informes;
    private javax.swing.JMenu jM_tareas;
    private javax.swing.JMenu jM_usuarios;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
