/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author InaRu
 */
public class InformesView extends javax.swing.JPanel {

    /**
     * Creates new form ProyectosView
     */
    public InformesView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaCLI_jpnl = new javax.swing.JPanel();
        imprimir2_btn = new javax.swing.JButton();
        jScrollP_Proy = new javax.swing.JScrollPane();
        reportPR_jTbl = new javax.swing.JTable();
        datosPR_pnl = new javax.swing.JPanel();
        jScrollP_Proy1 = new javax.swing.JScrollPane();
        reportEmpleado_jTbl = new javax.swing.JTable();
        imprimir1_btn = new javax.swing.JButton();

        setBackground(java.awt.SystemColor.controlHighlight);
        setMaximumSize(new java.awt.Dimension(750, 550));
        setMinimumSize(new java.awt.Dimension(750, 550));
        setPreferredSize(new java.awt.Dimension(750, 550));

        listaCLI_jpnl.setBackground(java.awt.SystemColor.controlHighlight);
        listaCLI_jpnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proyectos:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 204))); // NOI18N

        imprimir2_btn.setBackground(new java.awt.Color(0, 153, 204));
        imprimir2_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        imprimir2_btn.setForeground(new java.awt.Color(255, 255, 255));
        imprimir2_btn.setText("Imprimir");
        imprimir2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimir2_btnActionPerformed(evt);
            }
        });

        reportPR_jTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Proyecto", "Cliente", "Fecha inicio", "Fecha entrega", "Tarea"
            }
        ));
        jScrollP_Proy.setViewportView(reportPR_jTbl);

        javax.swing.GroupLayout listaCLI_jpnlLayout = new javax.swing.GroupLayout(listaCLI_jpnl);
        listaCLI_jpnl.setLayout(listaCLI_jpnlLayout);
        listaCLI_jpnlLayout.setHorizontalGroup(
            listaCLI_jpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaCLI_jpnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listaCLI_jpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollP_Proy, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                    .addGroup(listaCLI_jpnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(imprimir2_btn)))
                .addContainerGap())
        );
        listaCLI_jpnlLayout.setVerticalGroup(
            listaCLI_jpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaCLI_jpnlLayout.createSequentialGroup()
                .addComponent(jScrollP_Proy, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imprimir2_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        datosPR_pnl.setBackground(java.awt.SystemColor.controlHighlight);
        datosPR_pnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuarios:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 204))); // NOI18N

        reportEmpleado_jTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Tarea", "Estado", "Proyecto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        reportEmpleado_jTbl.getTableHeader().setReorderingAllowed(false);
        jScrollP_Proy1.setViewportView(reportEmpleado_jTbl);

        imprimir1_btn.setBackground(new java.awt.Color(0, 153, 204));
        imprimir1_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        imprimir1_btn.setForeground(new java.awt.Color(255, 255, 255));
        imprimir1_btn.setText("Imprimir");
        imprimir1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimir1_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout datosPR_pnlLayout = new javax.swing.GroupLayout(datosPR_pnl);
        datosPR_pnl.setLayout(datosPR_pnlLayout);
        datosPR_pnlLayout.setHorizontalGroup(
            datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosPR_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollP_Proy1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosPR_pnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(imprimir1_btn)))
                .addContainerGap())
        );
        datosPR_pnlLayout.setVerticalGroup(
            datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosPR_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollP_Proy1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imprimir1_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listaCLI_jpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(datosPR_pnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datosPR_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(listaCLI_jpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void imprimir1_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimir1_btnActionPerformed

    }//GEN-LAST:event_imprimir1_btnActionPerformed

    private void imprimir2_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimir2_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imprimir2_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel datosPR_pnl;
    private javax.swing.JButton imprimir1_btn;
    private javax.swing.JButton imprimir2_btn;
    private javax.swing.JScrollPane jScrollP_Proy;
    private javax.swing.JScrollPane jScrollP_Proy1;
    private javax.swing.JPanel listaCLI_jpnl;
    private javax.swing.JTable reportEmpleado_jTbl;
    private javax.swing.JTable reportPR_jTbl;
    // End of variables declaration//GEN-END:variables
}
