/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Conexion;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.JOptionPane;



/**
 *
 * @author InaRu
 */
public class LoginView extends javax.swing.JFrame implements ActionListener{
    
   
    

    /**
     * Creates new form NewJFrame
     */
    public LoginView() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar_login = new javax.swing.JToolBar();
        tituloLoginlb = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        username_txt = new javax.swing.JTextField();
        entrarbtn = new javax.swing.JButton();
        iconouserlbl = new javax.swing.JLabel();
        pass_jpass = new javax.swing.JPasswordField();
        usuario_lbl = new javax.swing.JLabel();
        pass_lbl = new javax.swing.JLabel();
        salirjBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("login");
        setName("loginJF"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar_login.setBackground(new java.awt.Color(51, 153, 255));
        jToolBar_login.setRollover(true);

        tituloLoginlb.setBackground(new java.awt.Color(255, 255, 255));
        tituloLoginlb.setForeground(new java.awt.Color(255, 255, 255));
        tituloLoginlb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tituloLoginlb.setLabelFor(tituloLoginlb);
        tituloLoginlb.setText("MEDICAL MANAGMENT SYSTEM");
        tituloLoginlb.setMaximumSize(new java.awt.Dimension(408, 35));
        tituloLoginlb.setPreferredSize(new java.awt.Dimension(48, 16));
        jToolBar_login.add(tituloLoginlb);

        getContentPane().add(jToolBar_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 38));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName(""); // NOI18N

        username_txt.setForeground(new java.awt.Color(204, 204, 204));
        username_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_txtActionPerformed(evt);
            }
        });

        entrarbtn.setBackground(new java.awt.Color(51, 153, 255));
        entrarbtn.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        entrarbtn.setForeground(new java.awt.Color(255, 255, 255));
        entrarbtn.setText("ENTRAR");
        entrarbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrarbtnMouseClicked(evt);
            }
        });
        entrarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarbtnActionPerformed(evt);
            }
        });

        iconouserlbl.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        iconouserlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/userblu.png"))); // NOI18N

        pass_jpass.setForeground(new java.awt.Color(204, 204, 204));

        usuario_lbl.setForeground(new java.awt.Color(0, 153, 255));
        usuario_lbl.setText("Usuario:");

        pass_lbl.setForeground(new java.awt.Color(0, 153, 255));
        pass_lbl.setText("Contraseña:");

        salirjBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1a.PNG"))); // NOI18N
        salirjBtn.setBorder(null);
        salirjBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salirjBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salirjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirjBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(salirjBtn)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(iconouserlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(327, 327, 327))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pass_lbl)
                            .addComponent(usuario_lbl))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(entrarbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                            .addComponent(username_txt)
                            .addComponent(pass_jpass))
                        .addGap(223, 223, 223))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(iconouserlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuario_lbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_jpass, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass_lbl))
                .addGap(29, 29, 29)
                .addComponent(entrarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(salirjBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 43, 750, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarbtnActionPerformed

        int resultado=0;
        
        try{
            
        Connection conex=null;
        Statement st=null;
        ResultSet rs=null;
        
        String pass=String.valueOf(pass_jpass.getPassword());
        String usuario=username_txt.getText(); 
        String sql;
        sql = "SELECT idUsuarios,nom_usuario FROM usuarios WHERE nom_usuario='"+usuario+"' and contrasenya='"+pass+"' ";
         conex=Conexion.conectarBD();
 
         
         
          st=conex.createStatement();
          rs=st.executeQuery(sql);

         
         if (rs.next()){
             resultado=1;
             if(resultado==1){
                 Home h = new Home();
                 h.setVisible(true);
                 this.dispose();
             }
             
              }else{
             
                  JOptionPane.showMessageDialog(null, "Acceso denegado! Usuario incorrecto");
                   }
            
            
        } catch (HeadlessException | SQLException e) {
            
            JOptionPane.showMessageDialog(null," Error:  " + e.getMessage());
        }
      
    }//GEN-LAST:event_entrarbtnActionPerformed

    private void username_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_txtActionPerformed

    private void entrarbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarbtnMouseClicked

                                                   
    }//GEN-LAST:event_entrarbtnMouseClicked

    private void salirjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirjBtnActionPerformed
        int dialog=JOptionPane.YES_NO_OPTION;
        int result=JOptionPane.showConfirmDialog(null,"Desea salir del programa?","Salir",dialog);
        if(result==0){
            System.exit(0);
        }
       
    }//GEN-LAST:event_salirjBtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
          //</editor-fold>
          //</editor-fold>
          //</editor-fold>
          //</editor-fold>
          //</editor-fold>
          //</editor-fold>
          //</editor-fold>
          //</editor-fold>
          
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entrarbtn;
    private javax.swing.JLabel iconouserlbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar_login;
    private javax.swing.JPasswordField pass_jpass;
    private javax.swing.JLabel pass_lbl;
    private javax.swing.JButton salirjBtn;
    private javax.swing.JLabel tituloLoginlb;
    private javax.swing.JTextField username_txt;
    private javax.swing.JLabel usuario_lbl;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
}
