/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author InaRu
 */
public class ProyectosView extends javax.swing.JPanel {

    /**
     * Creates new form ProyectosView
     */
    public ProyectosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionesProy_jpnl = new javax.swing.JPanel();
        nuevoPR_btn = new javax.swing.JButton();
        editPR_btn = new javax.swing.JButton();
        eliminarPR_btn = new javax.swing.JButton();
        guardarPR_btn = new javax.swing.JButton();
        salir_btn = new javax.swing.JButton();
        listaProy_jpnl = new javax.swing.JPanel();
        buscarProy_txt = new javax.swing.JTextField();
        buscarProy_btn = new javax.swing.JButton();
        jScrollP_Proy = new javax.swing.JScrollPane();
        proyectos_jTbl = new javax.swing.JTable();
        datosPR_pnl = new javax.swing.JPanel();
        codPR_lbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        codPR_txt = new javax.swing.JTextField();
        nomPR_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        estadoPR_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fechainiPR_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fechafinPR_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionPR_txt = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        tipoCombo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        clientePR_txt = new javax.swing.JTextField();

        setBackground(java.awt.SystemColor.controlHighlight);
        setMaximumSize(new java.awt.Dimension(750, 550));
        setMinimumSize(new java.awt.Dimension(750, 550));
        setPreferredSize(new java.awt.Dimension(750, 550));

        opcionesProy_jpnl.setBackground(java.awt.SystemColor.controlHighlight);
        opcionesProy_jpnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 102, 204))); // NOI18N

        nuevoPR_btn.setBackground(new java.awt.Color(0, 153, 255));
        nuevoPR_btn.setForeground(new java.awt.Color(255, 255, 255));
        nuevoPR_btn.setText("Nuevo");
        nuevoPR_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoPR_btnActionPerformed(evt);
            }
        });

        editPR_btn.setBackground(new java.awt.Color(0, 153, 255));
        editPR_btn.setForeground(new java.awt.Color(255, 255, 255));
        editPR_btn.setText("Editar");

        eliminarPR_btn.setBackground(new java.awt.Color(0, 153, 255));
        eliminarPR_btn.setForeground(new java.awt.Color(255, 255, 255));
        eliminarPR_btn.setText("Eliminar");

        guardarPR_btn.setBackground(new java.awt.Color(0, 153, 255));
        guardarPR_btn.setForeground(new java.awt.Color(255, 255, 255));
        guardarPR_btn.setText("Guardar");
        guardarPR_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarPR_btnActionPerformed(evt);
            }
        });

        salir_btn.setBackground(new java.awt.Color(0, 153, 255));
        salir_btn.setForeground(new java.awt.Color(255, 255, 255));
        salir_btn.setText("Salir");
        salir_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout opcionesProy_jpnlLayout = new javax.swing.GroupLayout(opcionesProy_jpnl);
        opcionesProy_jpnl.setLayout(opcionesProy_jpnlLayout);
        opcionesProy_jpnlLayout.setHorizontalGroup(
            opcionesProy_jpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opcionesProy_jpnlLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(opcionesProy_jpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salir_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardarPR_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarPR_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editPR_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevoPR_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        opcionesProy_jpnlLayout.setVerticalGroup(
            opcionesProy_jpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesProy_jpnlLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(nuevoPR_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editPR_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eliminarPR_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(guardarPR_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salir_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listaProy_jpnl.setBackground(java.awt.SystemColor.controlHighlight);
        listaProy_jpnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista proyectos:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 204))); // NOI18N

        buscarProy_btn.setBackground(new java.awt.Color(0, 153, 255));
        buscarProy_btn.setForeground(new java.awt.Color(255, 255, 255));
        buscarProy_btn.setText("Buscar");

        proyectos_jTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Estado", "Nombre", "Tipo", "Cliente", "Fecha inicio", "Fecha entrega", "Descripción"
            }
        ));
        jScrollP_Proy.setViewportView(proyectos_jTbl);
        if (proyectos_jTbl.getColumnModel().getColumnCount() > 0) {
            proyectos_jTbl.getColumnModel().getColumn(4).setHeaderValue("Cliente");
        }

        javax.swing.GroupLayout listaProy_jpnlLayout = new javax.swing.GroupLayout(listaProy_jpnl);
        listaProy_jpnl.setLayout(listaProy_jpnlLayout);
        listaProy_jpnlLayout.setHorizontalGroup(
            listaProy_jpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaProy_jpnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listaProy_jpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listaProy_jpnlLayout.createSequentialGroup()
                        .addComponent(jScrollP_Proy, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(listaProy_jpnlLayout.createSequentialGroup()
                        .addComponent(buscarProy_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarProy_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        listaProy_jpnlLayout.setVerticalGroup(
            listaProy_jpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaProy_jpnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listaProy_jpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarProy_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarProy_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollP_Proy, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        datosPR_pnl.setBackground(java.awt.SystemColor.controlHighlight);
        datosPR_pnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 204))); // NOI18N

        codPR_lbl.setText("Codigo:");

        jLabel1.setText("Nombre:");

        codPR_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codPR_txtActionPerformed(evt);
            }
        });

        jLabel2.setText("Estado:");

        jLabel3.setText("Fecha inicio: ");

        jLabel4.setText("Fecha entrega:");

        jLabel5.setText("Descripción:");

        descripcionPR_txt.setColumns(20);
        descripcionPR_txt.setRows(5);
        jScrollPane1.setViewportView(descripcionPR_txt);

        jLabel6.setText("Tipo:");

        tipoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Cliente:");

        javax.swing.GroupLayout datosPR_pnlLayout = new javax.swing.GroupLayout(datosPR_pnl);
        datosPR_pnl.setLayout(datosPR_pnlLayout);
        datosPR_pnlLayout.setHorizontalGroup(
            datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosPR_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosPR_pnlLayout.createSequentialGroup()
                        .addGroup(datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechainiPR_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientePR_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechafinPR_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(datosPR_pnlLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(datosPR_pnlLayout.createSequentialGroup()
                        .addGroup(datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(codPR_lbl))
                        .addGap(28, 28, 28)
                        .addGroup(datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(datosPR_pnlLayout.createSequentialGroup()
                                .addComponent(codPR_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel2)
                                .addGap(50, 50, 50)
                                .addComponent(estadoPR_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nomPR_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        datosPR_pnlLayout.setVerticalGroup(
            datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosPR_pnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codPR_lbl)
                    .addComponent(codPR_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(estadoPR_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomPR_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tipoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(clientePR_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fechainiPR_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(fechafinPR_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(datosPR_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datosPR_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionesProy_jpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(listaProy_jpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(datosPR_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(opcionesProy_jpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaProy_jpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoPR_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoPR_btnActionPerformed

    }//GEN-LAST:event_nuevoPR_btnActionPerformed

    private void guardarPR_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarPR_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarPR_btnActionPerformed

    private void salir_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salir_btnActionPerformed

    private void codPR_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codPR_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codPR_txtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarProy_btn;
    private javax.swing.JTextField buscarProy_txt;
    private javax.swing.JTextField clientePR_txt;
    private javax.swing.JLabel codPR_lbl;
    private javax.swing.JTextField codPR_txt;
    private javax.swing.JPanel datosPR_pnl;
    private javax.swing.JTextArea descripcionPR_txt;
    private javax.swing.JButton editPR_btn;
    private javax.swing.JButton eliminarPR_btn;
    private javax.swing.JTextField estadoPR_txt;
    private javax.swing.JTextField fechafinPR_txt;
    private javax.swing.JTextField fechainiPR_txt;
    private javax.swing.JButton guardarPR_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollP_Proy;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listaProy_jpnl;
    private javax.swing.JTextField nomPR_txt;
    private javax.swing.JButton nuevoPR_btn;
    private javax.swing.JPanel opcionesProy_jpnl;
    private javax.swing.JTable proyectos_jTbl;
    private javax.swing.JButton salir_btn;
    private javax.swing.JComboBox<String> tipoCombo;
    // End of variables declaration//GEN-END:variables
}
